#!/usr/bin/env python3
# https://boto3.readthedocs.io/en/latest/reference/services/organizations.html#client
"""
This will get the input and query all accounts within AWS Organizations.
input: stdin
output: dict

Example input:
{
  "source": {
    "active": "true",
    "rolename": "tf-admin",
    "assumerole": "tf-admin",
    "scope": "nn/ops",
    "organization_account": 286184583778
  },
  "version": {
    "id": "4b89115642f5486ec7df6e8614f0e137c3268b073caa461dffc28e69a4515276"
  }
}

Example output:
{}
"""

from __future__ import print_function
import boto3
import sys
import json
import yaml
import os

# Since reading stdout can only be performed once, we do it on initialization
save_stdin = json.loads(sys.stdin.read())

# The default output path for files on the host is passed via the first
# parameter ($1)
host_path = sys.argv[1]
# Check if base_path contains a normal path (with '.' or '/')
if '.' and '/' not in host_path:
    print("No path argument is given (as $1)", file=sys.stderr)
    sys.exit(1)

# Check mandatory parameters and error out if missing

if "'assumerole':" not in str(save_stdin):
    print("No mandatory assumerole parameter is given", file=sys.stderr)
    sys.exit(1)
if "'organization_account':" not in str(save_stdin):
    print("No mandatory organization_account parameter is given", file=sys.stderr)
    sys.exit(1)

def role_arn(assume_role, organization_account_id):
    """
    Generate the role arn to assume

    inputs: assume_role (str)
            organization_account_id(int)
    output: iam role arn (str)
    """
    # build arn for role
    return str("arn:aws:iam::" + str(organization_account_id) + ":role/" + assume_role)

def role_arn_to_session(**args):
    """
    Assume a role

    inputs:  RoleArn(str)
             RoleSessionName(str)
             boto3.client.assume_role(**args)
    outputs: boto3.Session
    usage  :
            session = role_arn_to_session(
                RoleArn='arn:aws:iam::012345678901:role/example-role',
                RoleSessionName='ExampleSessionName')
            client = session.client('organizations')
    """
    client = boto3.client('sts')
    response = client.assume_role(**args)
    return boto3.Session(
        aws_access_key_id=response['Credentials']['AccessKeyId'],
        aws_secret_access_key=response['Credentials']['SecretAccessKey'],
        aws_session_token=response['Credentials']['SessionToken'])

def describe_organization():
    """
    Generate a org accounts config file using AWS Organizations.
    This method looks up data from the stdin and describes the organizations
    accounts using the methods
    role_arn
    role_arn_to_session
    get_ou_from_path
    get_accounts_for_ou
    where the last method leverages get_sub_ous
    inputs: -
    output: list of accounts for given paths
    """
    # Role template for accounts in the config
    if "'rolename':" not in str(save_stdin):
        rolename = "tf-admin"
        print("Rolename is defaulted to " + str(rolename), file=sys.stderr)
    else:
        rolename = list(save_stdin['source']['rolename'])
        print("Rolename set is " + str(rolename), file=sys.stderr)

    role = str("arn:aws:iam::{Id}:role/" + rolename)

    # needed to setup the session to the org
    assume_role = str(save_stdin['source']['assumerole'])
    organization_account_id = str(save_stdin['source']['organization_account'])

    # If scope is specified, take only the tree for a specific scope. Otherwise use the default root path ("/")
    # scope does support multiple entries in the format list
    if "'scope':" not in str(save_stdin):
        ou = "/"
        print("Scope set is root", file=sys.stderr)
    else:
        ou = list(save_stdin['source']['scope'])
        print("Scope is set to the following list of paths: " + str(ou), file=sys.stderr)

    # If active is specified to true, get only active accounts. Defaults to False
    if "'active':" not in str(save_stdin):
        active = False
    else:
        if str(save_stdin['source']['active']) in ["True","true",True]:
            active = True
        else:
            active = False
    print("Only include active accounts : " + str(active), file=sys.stderr)

    # set the role arn
    role_arn_str = role_arn(assume_role, organization_account_id)

    # set the session to assume role
    session = role_arn_to_session(
        RoleArn=role_arn_str,
        RoleSessionName='listAccountsSession')

    # build session
    client = session.client('organizations')

    accounts = []
    for path in ou:
        print("Querying out path " + path, file=sys.stderr)
        ou = get_ou_from_path(client, path)
        accounts.extend(get_accounts_for_ou(client, ou, active))

    results = []
    for a in accounts:
        tags = []
        path_parts = a['Path'].strip('/').split('/')
        for idx, _ in enumerate(path_parts):
            tags.append("path:/%s" % "/".join(path_parts[:idx + 1]))

        ainfo = {
            'account_id': a['Id'],
            'email': a['Email'],
            'name': a['Name'],
            'paths': tags,
            'role': role.format(**a)}
        results.append(ainfo)

    # print(
    #     yaml.safe_dump(
    #         {'accounts': results},
    #         default_flow_style=False), file=sys.stderr
    #
    # )

    results = yaml.safe_dump(
            {'accounts': results},
            default_flow_style=False
        )

    return results


def get_ou_from_path(client, path):
    """
    use the path to find the ou id

    inputs:  client (the session)
             path(str)

    outputs: ou
    """
    ou = client.list_roots()['Roots'][0]

    if path == "/":
        ou['Path'] = path
        return ou

    ou_pager = client.get_paginator('list_organizational_units_for_parent')
    for part in path.strip('/').split('/'):
        found = False
        for page in ou_pager.paginate(ParentId=ou['Id']):
            for child in page.get('OrganizationalUnits'):
                if child['Name'] == part:
                    found = True
                    ou = child
                    break
            if found:
                break
        if found is False:
            raise ValueError(
                "No OU named:%r found in path: %s" % (
                    path, path))
    ou['Path'] = path
    return ou


def get_accounts_for_ou(client, ou, active, recursive=True):
    """
    use the ou to find the accounts under it.
    Also find sub ous then list their accounts

    inputs:  client (the session)
             ou(str)
             active(bool)
             recursive(bool)

    outputs: results(list) list of accounts
    """
    results = []
    ous = [ou]
    if recursive:
        ous = get_sub_ous(client, ou)

    account_pager = client.get_paginator('list_accounts_for_parent')
    for ou in ous:
        for a in account_pager.paginate(
            ParentId=ou['Id']).build_full_result().get(
                'Accounts', []):
            a['Path'] = ou['Path']
            if active:
                if a['Status'] == 'ACTIVE':
                    results.append(a)
            else:
                results.append(a)
    return results

def get_sub_ous(client, ou):
    """
    Find sub ous then list their accounts

    inputs:  client (the session)
             ou(str)

    outputs: results(list) list of sub ous
    """
    results = [ou]
    ou_pager = client.get_paginator('list_organizational_units_for_parent')
    for sub_ou in ou_pager.paginate(
            ParentId=ou['Id']).build_full_result().get(
                'OrganizationalUnits'):
        sub_ou['Path'] = "/%s/%s" % (ou['Path'].strip('/'), sub_ou['Name'])
        results.extend(get_sub_ous(client, sub_ou))
    return results

def write_output_file(base_path):
    """
    Generate a file called "$1/org-accounts.yml" with all accounts from the organization

    inputs: host path to output files (str)
    output: AWS Organizations account list (file, json)
    """
    output_path = os.path.join(base_path, 'accounts.yml')
    accounts = describe_organization()

    # Write the raw account structure to a file named 'org-accounts.yml'
    with open(output_path, 'w') as outfile:
        print(accounts, file=outfile)

# generate output for stdout; this is needed for Concourse
print(json.dumps(save_stdin))

# Deliver the output file
write_output_file(host_path)
